/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface MarginCollateralInterface extends utils.Interface {
  contractName: "MarginCollateral";
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "MARGIN_ADMIN()": FunctionFragment;
    "accountPrice(address)": FunctionFragment;
    "addBorrowToken(address[])": FunctionFragment;
    "addCollateral(address,uint256)": FunctionFragment;
    "addCollateralToken(address[])": FunctionFragment;
    "borrowed(address,address)": FunctionFragment;
    "borrowedPrice(address)": FunctionFragment;
    "collateral(address,address)": FunctionFragment;
    "collateralPrice(address)": FunctionFragment;
    "currentLeverage(address)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "initialBorrowPrice(address,address)": FunctionFragment;
    "initializeMarginCore(address,address)": FunctionFragment;
    "initializeMarginLevel(uint256,uint256)": FunctionFragment;
    "initializeMarginLimits(uint256)": FunctionFragment;
    "interest(address)": FunctionFragment;
    "isApprovedBorrowToken(address)": FunctionFragment;
    "isApprovedCollateralToken(address)": FunctionFragment;
    "isBorrowToken(address)": FunctionFragment;
    "isCollateralToken(address)": FunctionFragment;
    "liquidatable(address)": FunctionFragment;
    "marginLevel(address)": FunctionFragment;
    "maxLeverage()": FunctionFragment;
    "minCollateralPrice()": FunctionFragment;
    "minMarginLevel()": FunctionFragment;
    "oracle()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "pool()": FunctionFragment;
    "removeCollateral(address,uint256)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "resettable(address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setApprovedBorrowToken(address[],bool[])": FunctionFragment;
    "setApprovedCollateralToken(address[],bool[])": FunctionFragment;
    "setMaxLeverage(uint256,uint256)": FunctionFragment;
    "setMinCollateralPrice(uint256)": FunctionFragment;
    "setOracle(address)": FunctionFragment;
    "setPool(address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "totalBorrowed(address)": FunctionFragment;
    "totalCollateral(address)": FunctionFragment;
    "unpause()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MARGIN_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accountPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addBorrowToken",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addCollateral",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addCollateralToken",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowed",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowedPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "collateral",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "currentLeverage",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialBorrowPrice",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeMarginCore",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeMarginLevel",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeMarginLimits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "interest", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isApprovedBorrowToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedCollateralToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isBorrowToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isCollateralToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidatable",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "marginLevel", values: [string]): string;
  encodeFunctionData(
    functionFragment: "maxLeverage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minCollateralPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minMarginLevel",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeCollateral",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "resettable", values: [string]): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovedBorrowToken",
    values: [string[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovedCollateralToken",
    values: [string[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxLeverage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinCollateralPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setOracle", values: [string]): string;
  encodeFunctionData(functionFragment: "setPool", values: [string]): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBorrowed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCollateral",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MARGIN_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addBorrowToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCollateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrowed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "borrowedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "collateral", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentLeverage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialBorrowPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeMarginCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeMarginLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeMarginLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "interest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedBorrowToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedCollateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBorrowToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCollateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidatable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marginLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxLeverage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minCollateralPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minMarginLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resettable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setApprovedBorrowToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovedCollateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxLeverage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinCollateralPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBorrowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;

  events: {
    "AddCollateral(address,address,uint256)": EventFragment;
    "Paused(address)": EventFragment;
    "RemoveCollateral(address,address,uint256)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddCollateral"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemoveCollateral"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export type AddCollateralEvent = TypedEvent<
  [string, string, BigNumber],
  { account: string; token: string; amount: BigNumber }
>;

export type AddCollateralEventFilter = TypedEventFilter<AddCollateralEvent>;

export type PausedEvent = TypedEvent<[string], { account: string }>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export type RemoveCollateralEvent = TypedEvent<
  [string, string, BigNumber],
  { account: string; token: string; amount: BigNumber }
>;

export type RemoveCollateralEventFilter =
  TypedEventFilter<RemoveCollateralEvent>;

export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  { role: string; previousAdminRole: string; newAdminRole: string }
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  { role: string; account: string; sender: string }
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  { role: string; account: string; sender: string }
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export type UnpausedEvent = TypedEvent<[string], { account: string }>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface MarginCollateral extends BaseContract {
  contractName: "MarginCollateral";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MarginCollateralInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    MARGIN_ADMIN(overrides?: CallOverrides): Promise<[string]>;

    accountPrice(
      account_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    addBorrowToken(
      token_: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addCollateral(
      token_: string,
      amount_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addCollateralToken(
      token_: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    borrowed(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    borrowedPrice(
      account_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    collateral(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    collateralPrice(
      account_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    currentLeverage(
      account_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "initialBorrowPrice(address,address)"(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "initialBorrowPrice(address)"(
      account_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    initializeMarginCore(
      pool_: string,
      oracle_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initializeMarginLevel(
      maxLeverageNumerator_: BigNumberish,
      maxLeverageDenominator_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initializeMarginLimits(
      minCollateralPrice_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "interest(address)"(
      account_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "interest(address,address)"(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isApprovedBorrowToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isApprovedCollateralToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isBorrowToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isCollateralToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    liquidatable(
      account_: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    marginLevel(
      account_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    maxLeverage(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

    minCollateralPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    minMarginLevel(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    pool(overrides?: CallOverrides): Promise<[string]>;

    removeCollateral(
      token_: string,
      amount_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    resettable(account_: string, overrides?: CallOverrides): Promise<[boolean]>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setApprovedBorrowToken(
      token_: string[],
      approved_: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setApprovedCollateralToken(
      token_: string[],
      approved_: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxLeverage(
      maxLeverageNumerator_: BigNumberish,
      maxLeverageDenominator_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMinCollateralPrice(
      minCollateralPrice_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOracle(
      oracle_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPool(
      pool_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    totalBorrowed(
      token_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalCollateral(
      token_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  MARGIN_ADMIN(overrides?: CallOverrides): Promise<string>;

  accountPrice(account_: string, overrides?: CallOverrides): Promise<BigNumber>;

  addBorrowToken(
    token_: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addCollateral(
    token_: string,
    amount_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addCollateralToken(
    token_: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  borrowed(
    token_: string,
    account_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  borrowedPrice(
    account_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  collateral(
    token_: string,
    account_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  collateralPrice(
    account_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  currentLeverage(
    account_: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "initialBorrowPrice(address,address)"(
    token_: string,
    account_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "initialBorrowPrice(address)"(
    account_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  initializeMarginCore(
    pool_: string,
    oracle_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initializeMarginLevel(
    maxLeverageNumerator_: BigNumberish,
    maxLeverageDenominator_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initializeMarginLimits(
    minCollateralPrice_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "interest(address)"(
    account_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "interest(address,address)"(
    token_: string,
    account_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isApprovedBorrowToken(
    token_: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isApprovedCollateralToken(
    token_: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isBorrowToken(token_: string, overrides?: CallOverrides): Promise<boolean>;

  isCollateralToken(
    token_: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  liquidatable(account_: string, overrides?: CallOverrides): Promise<boolean>;

  marginLevel(
    account_: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  maxLeverage(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

  minCollateralPrice(overrides?: CallOverrides): Promise<BigNumber>;

  minMarginLevel(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

  oracle(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  pool(overrides?: CallOverrides): Promise<string>;

  removeCollateral(
    token_: string,
    amount_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  resettable(account_: string, overrides?: CallOverrides): Promise<boolean>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setApprovedBorrowToken(
    token_: string[],
    approved_: boolean[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setApprovedCollateralToken(
    token_: string[],
    approved_: boolean[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxLeverage(
    maxLeverageNumerator_: BigNumberish,
    maxLeverageDenominator_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMinCollateralPrice(
    minCollateralPrice_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOracle(
    oracle_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPool(
    pool_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  totalBorrowed(token_: string, overrides?: CallOverrides): Promise<BigNumber>;

  totalCollateral(
    token_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    MARGIN_ADMIN(overrides?: CallOverrides): Promise<string>;

    accountPrice(
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addBorrowToken(token_: string[], overrides?: CallOverrides): Promise<void>;

    addCollateral(
      token_: string,
      amount_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    addCollateralToken(
      token_: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    borrowed(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    borrowedPrice(
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collateral(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collateralPrice(
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currentLeverage(
      account_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "initialBorrowPrice(address,address)"(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "initialBorrowPrice(address)"(
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initializeMarginCore(
      pool_: string,
      oracle_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    initializeMarginLevel(
      maxLeverageNumerator_: BigNumberish,
      maxLeverageDenominator_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    initializeMarginLimits(
      minCollateralPrice_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "interest(address)"(
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "interest(address,address)"(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedBorrowToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isApprovedCollateralToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isBorrowToken(token_: string, overrides?: CallOverrides): Promise<boolean>;

    isCollateralToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    liquidatable(account_: string, overrides?: CallOverrides): Promise<boolean>;

    marginLevel(
      account_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    maxLeverage(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

    minCollateralPrice(overrides?: CallOverrides): Promise<BigNumber>;

    minMarginLevel(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

    oracle(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    pool(overrides?: CallOverrides): Promise<string>;

    removeCollateral(
      token_: string,
      amount_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    resettable(account_: string, overrides?: CallOverrides): Promise<boolean>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovedBorrowToken(
      token_: string[],
      approved_: boolean[],
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovedCollateralToken(
      token_: string[],
      approved_: boolean[],
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxLeverage(
      maxLeverageNumerator_: BigNumberish,
      maxLeverageDenominator_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinCollateralPrice(
      minCollateralPrice_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setOracle(oracle_: string, overrides?: CallOverrides): Promise<void>;

    setPool(pool_: string, overrides?: CallOverrides): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    totalBorrowed(
      token_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalCollateral(
      token_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AddCollateral(address,address,uint256)"(
      account?: string | null,
      token?: null,
      amount?: null
    ): AddCollateralEventFilter;
    AddCollateral(
      account?: string | null,
      token?: null,
      amount?: null
    ): AddCollateralEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "RemoveCollateral(address,address,uint256)"(
      account?: string | null,
      token?: null,
      amount?: null
    ): RemoveCollateralEventFilter;
    RemoveCollateral(
      account?: string | null,
      token?: null,
      amount?: null
    ): RemoveCollateralEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    MARGIN_ADMIN(overrides?: CallOverrides): Promise<BigNumber>;

    accountPrice(
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addBorrowToken(
      token_: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addCollateral(
      token_: string,
      amount_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addCollateralToken(
      token_: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    borrowed(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    borrowedPrice(
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collateral(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collateralPrice(
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currentLeverage(
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "initialBorrowPrice(address,address)"(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "initialBorrowPrice(address)"(
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initializeMarginCore(
      pool_: string,
      oracle_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initializeMarginLevel(
      maxLeverageNumerator_: BigNumberish,
      maxLeverageDenominator_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initializeMarginLimits(
      minCollateralPrice_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "interest(address)"(
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "interest(address,address)"(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedBorrowToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedCollateralToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isBorrowToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isCollateralToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidatable(
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    marginLevel(
      account_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxLeverage(overrides?: CallOverrides): Promise<BigNumber>;

    minCollateralPrice(overrides?: CallOverrides): Promise<BigNumber>;

    minMarginLevel(overrides?: CallOverrides): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    pool(overrides?: CallOverrides): Promise<BigNumber>;

    removeCollateral(
      token_: string,
      amount_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    resettable(account_: string, overrides?: CallOverrides): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setApprovedBorrowToken(
      token_: string[],
      approved_: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setApprovedCollateralToken(
      token_: string[],
      approved_: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxLeverage(
      maxLeverageNumerator_: BigNumberish,
      maxLeverageDenominator_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMinCollateralPrice(
      minCollateralPrice_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOracle(
      oracle_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPool(
      pool_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalBorrowed(
      token_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalCollateral(
      token_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MARGIN_ADMIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    accountPrice(
      account_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addBorrowToken(
      token_: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addCollateral(
      token_: string,
      amount_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addCollateralToken(
      token_: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    borrowed(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    borrowedPrice(
      account_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collateral(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collateralPrice(
      account_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currentLeverage(
      account_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "initialBorrowPrice(address,address)"(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "initialBorrowPrice(address)"(
      account_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initializeMarginCore(
      pool_: string,
      oracle_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initializeMarginLevel(
      maxLeverageNumerator_: BigNumberish,
      maxLeverageDenominator_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initializeMarginLimits(
      minCollateralPrice_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "interest(address)"(
      account_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "interest(address,address)"(
      token_: string,
      account_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isApprovedBorrowToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isApprovedCollateralToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isBorrowToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isCollateralToken(
      token_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidatable(
      account_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    marginLevel(
      account_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxLeverage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minCollateralPrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minMarginLevel(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeCollateral(
      token_: string,
      amount_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    resettable(
      account_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setApprovedBorrowToken(
      token_: string[],
      approved_: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setApprovedCollateralToken(
      token_: string[],
      approved_: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxLeverage(
      maxLeverageNumerator_: BigNumberish,
      maxLeverageDenominator_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMinCollateralPrice(
      minCollateralPrice_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOracle(
      oracle_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPool(
      pool_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalBorrowed(
      token_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalCollateral(
      token_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
