/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TreasurerEpochInterface extends utils.Interface {
  contractName: "TreasurerEpoch";
  functions: {
    "epochId()": FunctionFragment;
    "epochTime(uint256)": FunctionFragment;
    "epochTotalAmountStaked(address,uint256)": FunctionFragment;
    "epochTotalMintedReserveTokens(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "epochId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "epochTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochTotalAmountStaked",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochTotalMintedReserveTokens",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "epochId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "epochTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "epochTotalAmountStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochTotalMintedReserveTokens",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TreasurerEpoch extends BaseContract {
  contractName: "TreasurerEpoch";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TreasurerEpochInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    epochId(overrides?: CallOverrides): Promise<[BigNumber]>;

    epochTime(
      epochId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    epochTotalAmountStaked(
      token_: string,
      epochId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    epochTotalMintedReserveTokens(
      epochId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  epochId(overrides?: CallOverrides): Promise<BigNumber>;

  epochTime(
    epochId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  epochTotalAmountStaked(
    token_: string,
    epochId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  epochTotalMintedReserveTokens(
    epochId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    epochId(overrides?: CallOverrides): Promise<BigNumber>;

    epochTime(
      epochId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    epochTotalAmountStaked(
      token_: string,
      epochId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    epochTotalMintedReserveTokens(
      epochId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    epochId(overrides?: CallOverrides): Promise<BigNumber>;

    epochTime(
      epochId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    epochTotalAmountStaked(
      token_: string,
      epochId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    epochTotalMintedReserveTokens(
      epochId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    epochId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    epochTime(
      epochId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    epochTotalAmountStaked(
      token_: string,
      epochId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    epochTotalMintedReserveTokens(
      epochId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
